# Generated by Django 2.2.3 on 2019-07-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_assessment_total', models.IntegerField()),
                ('practical_final_total', models.IntegerField()),
                ('theory_assessment_total', models.IntegerField()),
                ('theory_final_total', models.IntegerField()),
                ('marks_final_total', models.IntegerField()),
                ('theory_duration_hours', models.DecimalField(decimal_places=1, max_digits=2)),
                ('practical_duration_hours', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=200)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_code', models.CharField(max_length=25)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(max_length=50)),
                ('no_of_hours', models.DecimalField(decimal_places=1, max_digits=2)),
                ('lecture_hours', models.DecimalField(decimal_places=1, max_digits=2)),
                ('tutorial_hours', models.DecimalField(decimal_places=1, max_digits=2)),
                ('practical_hours', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('part', models.IntegerField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.Program')),
            ],
        ),
    ]
