# Generated by Django 2.2.3 on 2019-07-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name_plural': 'Marks'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'Syllabus'},
        ),
    ]
