# Generated by Django 2.2.3 on 2019-07-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_auto_20190719_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_entry.Subject'),
            preserve_default=False,
        ),
    ]
