# Generated by Django 2.2.3 on 2019-07-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_auto_20190719_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='no_of_hours',
        ),
    ]
