# Generated by Django 2.2.3 on 2019-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_remove_subject_no_of_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='no_of_hours',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.ManyToManyField(to='data_entry.Syllabus'),
        ),
    ]
