# Generated by Django 2.2.3 on 2019-07-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_auto_20190722_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='no_of_hours',
            new_name='Total_no_of_hours',
        ),
    ]
