# Generated by Django 2.2.3 on 2019-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_auto_20190722_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ManyToManyField(to='data_entry.Subject'),
        ),
    ]
