# Generated by Django 2.2.3 on 2019-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0008_auto_20190722_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.ManyToManyField(to='data_entry.Syllabus'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='program',
            field=models.ManyToManyField(to='data_entry.Program'),
        ),
    ]
