# Generated by Django 2.2.3 on 2019-07-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0009_auto_20190722_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='total_lecture_hr',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='total_practical_assessment_marks',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='total_practical_duration_hour',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='total_practical_hr',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='total_practical_marks',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='total_theory_assessment_marks',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='total_theory_duration_hour',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='total_theory_marks',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='total_tutorial_hr',
        ),
    ]
