# Generated by Django 2.2.3 on 2019-07-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0010_auto_20190723_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_type',
            field=models.CharField(default='T', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_name',
            field=models.CharField(default='T', help_text='BCT_I_I_Part', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(help_text='Compulsory', max_length=50),
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='program',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='program',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='data_entry.Program'),
            preserve_default=False,
        ),
    ]
