# Generated by Django 2.2.3 on 2019-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0011_auto_20190725_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='exam_type',
            field=models.IntegerField(choices=[(1, 'THEORY'), (2, 'PRACTICAL'), (3, 'BOTH')], default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.IntegerField(choices=[(1, 'Compulsory'), (2, 'Elective')], default=1),
        ),
    ]
