# Generated by Django 2.2.3 on 2019-08-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0012_auto_20190805_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='exam_type',
            field=models.CharField(choices=[('T', 'THEORY'), ('P', 'PRACTICAL'), ('B', 'BOTH')], default='Theory', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective')], default='COMPULSORY', max_length=20),
        ),
    ]
