# Generated by Django 2.2.3 on 2019-08-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0014_auto_20190816_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_entry.Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='marks_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='data_entry.Marks'),
            preserve_default=False,
        ),
    ]
