# Generated by Django 2.2.3 on 2019-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0015_auto_20190816_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='marks_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='marks_final_total',
            field=models.IntegerField(default=750),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_assessment_total',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_duration_hours',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_final_total',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_assessment_total',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_duration_hours',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_final_total',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
