# Generated by Django 2.2.3 on 2019-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry_masters', '0002_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='total_credits',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
