# Generated by Django 2.2.3 on 2019-08-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry_masters', '0003_syllabus_total_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_name',
        ),
    ]
