# Generated by Django 2.2.3 on 2019-08-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry_masters', '0004_remove_syllabus_syllabus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective I', 'Elective I'), ('Elective II', 'Elective II'), ('Elective III', 'Elective III'), ('Optional', 'Optional')], default='COMPULSORY', max_length=20),
        ),
    ]
